baseurl = "http://xn----etbmd0adcciehjlf.xn--p1ai/"
languageCode = "en-us"
title = "Горизонт"
theme = "hyde"

[params]
themeColor = "theme-base-0f"
description = "Муниципальное бюджетное учреждение «Спортивный Клуб Горизонт» города Магнитогорска"
locale = "ru-ru"

